
import { Suspense } from 'react';
import ClientPageWrapper from './ClientPageWrapper'

// Precomputed slugs
const allSlugs = [
  ["apparel"],
  ["baby-care"],
  ["bakery-cakes-dairy"],
  ["beauty-hygiene"],
  ["beverages"],
  ["cleaning-household"],
  ["eggs-meat-fish"],
  ["electronics"],
  ["fashion"],
  ["food-court"],
  ["foodgrains-oil-masala"],
  ["fruits-vegetables"],
  ["gourmet-world-food"],
  ["kitchen-garden-pets"],
  ["paan-corner"],
  ["snacks-branded-foods"],

  ["apparel", "mens-apparel"],
  ["apparel", "womens-apparel"],
  ["baby-care", "baby-accessories"],
  ["baby-care", "baby-bath-hygiene"],
  ["baby-care", "baby-food-formula"],
  ["baby-care", "diapers-wipes"],
  ["baby-care", "feeding-nursing"],
  ["baby-care", "mothers-maternity"],
  ["bakery-cakes-dairy", "bakery-snacks"],
  ["bakery-cakes-dairy", "breads-buns"],
  ["bakery-cakes-dairy", "cakes-pastries"],
  ["bakery-cakes-dairy", "cookies-rusk-khari"],
  ["bakery-cakes-dairy", "dairy"],
  ["bakery-cakes-dairy", "gourmet-breads"],
  ["bakery-cakes-dairy", "ice-creams-desserts"],
  ["bakery-cakes-dairy", "non-dairy"],
  ["beauty-hygiene", "bath-hand-wash"],
  ["beauty-hygiene", "feminine-hygiene"],
  ["beauty-hygiene", "fragrances-deos"],
  ["beauty-hygiene", "hair-care"],
  ["beauty-hygiene", "health-medicine"],
  ["beauty-hygiene", "makeup"],
  ["beauty-hygiene", "mens-grooming"],
  ["beauty-hygiene", "oral-care"],
  ["beauty-hygiene", "sexual-wellness"],
  ["beauty-hygiene", "skin-care"],
  ["beverages", "coffee"],
  ["beverages", "energy-soft-drinks"],
  ["beverages", "fruit-juices-drinks"],
  ["beverages", "health-drink-supplement"],
  ["beverages", "tea"],
  ["beverages", "water"],
  ["cleaning-household", "all-purpose-cleaners"],
  ["cleaning-household", "bins-bathroom-ware"],
  ["cleaning-household", "car-shoe-care"],
  ["cleaning-household", "detergents-dishwash"],
  ["cleaning-household", "disposables-garbage-bag"],
  ["cleaning-household", "fresheners-repellents"],
  ["cleaning-household", "mops-brushes-scrubs"],
  ["cleaning-household", "party-festive-needs"],
  ["cleaning-household", "pooja-needs"],
  ["cleaning-household", "sports-fitness"],
  ["cleaning-household", "stationery"],
  ["cleaning-household", "toys-games"],
  ["eggs-meat-fish", "eggs"],
  ["eggs-meat-fish", "fish-seafood"],
  ["eggs-meat-fish", "marinades"],
  ["eggs-meat-fish", "mutton-lamb"],
  ["eggs-meat-fish", "pork-other-meats"],
  ["eggs-meat-fish", "poultry"],
  ["eggs-meat-fish", "sausages-bacon-salami"],
  ["electronics", "audio-devices"],
  ["electronics", "beauty-grooming"],
  ["electronics", "cameras-accessories"],
  ["electronics", "electrical-accessories"],
  ["electronics", "home-kitchen-appliance"],
  ["electronics", "home-appliances"],
  ["electronics", "kitchen-appliances"],
  ["electronics", "phone-laptop-accessory"],
  ["electronics", "phone-laptop-tablets"],
  ["electronics", "smart-wearables"],
  ["fashion", "fashion-essentials"],
  ["fashion", "footwear"],
  ["fashion", "kids-apparel"],
  ["fashion", "mens-apparel"],
  ["fashion", "travel"],
  ["fashion", "womens-apparel"],
  ["food-court", "burgers-sandwiches"],
  ["food-court", "cake-pastry-delights"],
  ["food-court", "cold-beverages"],
  ["food-court", "hot-beverages"],
  ["food-court", "rolls-wraps"],
  ["food-court", "snack-time"],
  ["foodgrains-oil-masala", "atta-flours-sooji"],
  ["foodgrains-oil-masala", "dals-pulses"],
  ["foodgrains-oil-masala", "dry-fruits"],
  ["foodgrains-oil-masala", "edible-oils-ghee"],
  ["foodgrains-oil-masala", "masalas-spices"],
  ["foodgrains-oil-masala", "organic-staples"],
  ["foodgrains-oil-masala", "rice-rice-products"],
  ["foodgrains-oil-masala", "salt-sugar-jaggery"],
  ["fruits-vegetables", "cuts-sprouts"],
  ["fruits-vegetables", "exotic-fruits-veggies"],
  ["fruits-vegetables", "flower-bouquets-bunches"],
  ["fruits-vegetables", "fresh-fruits"],
  ["fruits-vegetables", "fresh-vegetables"],
  ["fruits-vegetables", "herbs-seasonings"],
  ["fruits-vegetables", "organic-fruits-vegetables"],
  ["gourmet-world-food", "cereals-breakfast"],
  ["gourmet-world-food", "chocolates-biscuits"],
  ["gourmet-world-food", "cooking-baking-needs"],
  ["gourmet-world-food", "dairy-cheese"],
  ["gourmet-world-food", "drinks-beverages"],
  ["gourmet-world-food", "oils-vinegar"],
  ["gourmet-world-food", "pasta-soup-noodles"],
  ["gourmet-world-food", "sauces-spreads-dips"],
  ["gourmet-world-food", "snacks-dry-fruits-nuts"],
  ["gourmet-world-food", "tinned-processed-food"],
  ["kitchen-garden-pets", "appliances-electricals"],
  ["kitchen-garden-pets", "bakeware"],
  ["kitchen-garden-pets", "cookware-non-stick"],
  ["kitchen-garden-pets", "crockery-cutlery"],
  ["kitchen-garden-pets", "electronics-devices"],
  ["kitchen-garden-pets", "flask-casserole"],
  ["kitchen-garden-pets", "gardening"],
  ["kitchen-garden-pets", "home-furnishing"],
  ["kitchen-garden-pets", "kitchen-accessories"],
  ["kitchen-garden-pets", "pet-food-accessories"],
  ["kitchen-garden-pets", "steel-utensils"],
  ["kitchen-garden-pets", "storage-accessories"],
  ["paan-corner", "smoking-supplies"],
  ["snacks-branded-foods", "biscuits-cookies"],
  ["snacks-branded-foods", "breakfast-cereals"],
  ["snacks-branded-foods", "chocolates-candies"],
  ["snacks-branded-foods", "frozen-veggies-snacks"],
  ["snacks-branded-foods", "indian-mithai"],
  ["snacks-branded-foods", "noodle-pasta-vermicelli"],
  ["snacks-branded-foods", "pickles-chutney"],
  ["snacks-branded-foods", "ready-to-cook-eat"],
  ["snacks-branded-foods", "snacks-namkeen"],
  ["snacks-branded-foods", "spreads-sauces-ketchup"]
];

// Generate all paths statically
export async function generateStaticParams() {
  return allSlugs.map(slug => ({ slug }));
}

// Wrap and render the client component
export default function Page() {
  return <Suspense fallback={<div>Loading...</div>}><ClientPageWrapper /></Suspense>;
}
